# Generated by Django 2.1.1 on 2018-09-13 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GeneralApp', '0004_auto_20180913_1750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='Имя',
            new_name='Name',
        ),
    ]
