# Generated by Django 2.1.1 on 2018-09-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='Имя',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
