# Generated by Django 2.1.1 on 2018-09-13 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20180913_1741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='Email',
            new_name='email_model',
        ),
    ]
