# Generated by Django 2.1.1 on 2018-09-13 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0003_auto_20180913_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='email_model',
            new_name='Email',
        ),
    ]
