# Generated by Django 2.1.1 on 2018-10-12 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0007_auto_20180916_0119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Человек', 'verbose_name_plural': 'Люди'},
        ),
        migrations.RenameField(
            model_name='person',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='Note',
            new_name='note',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='Time',
            new_name='time',
        ),
    ]
