# Generated by Django 2.1.1 on 2018-10-14 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0008_auto_20181013_0009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Человек из формы обратной связи', 'verbose_name_plural': 'Люди из формы обратной связи'},
        ),
    ]
