# Generated by Django 2.1.1 on 2018-09-16 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20180916_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=8),
        ),
        migrations.AddField(
            model_name='productinorder',
            name='price_per_item',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=7),
        ),
        migrations.AddField(
            model_name='productinorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=8),
        ),
    ]
