# Generated by Django 2.1.1 on 2018-09-17 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20180917_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinorder',
            name='is_active',
        ),
    ]
