# Generated by Django 2.1.1 on 2018-09-18 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20180918_0716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Product',
        ),
    ]
