# Generated by Django 2.1.1 on 2018-09-18 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20180918_0727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinorder',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='ProductInOrder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.ProductInOrder'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='number',
            field=models.IntegerField(),
        ),
    ]
