# Generated by Django 2.1.1 on 2018-09-18 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20180918_0758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ProductInOrder',
        ),
        migrations.AddField(
            model_name='productinorder',
            name='order',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Order'),
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
