# Generated by Django 2.1.1 on 2018-09-16 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='number',
        ),
    ]
