# Generated by Django 2.1.1 on 2018-10-09 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20181009_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.ForeignKey(null=1, on_delete=django.db.models.deletion.CASCADE, to='products.ProductType'),
            preserve_default=1,
        ),
    ]
