# Generated by Django 2.1.1 on 2018-10-14 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_full_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
    ]
