# Generated by Django 2.1.1 on 2018-10-14 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_product_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='is_active',
            new_name='is_aviable',
        ),
    ]
