# Generated by Django 2.1.1 on 2018-10-14 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20181014_2051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='is_aviable',
            new_name='is_available',
        ),
    ]
